# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Juan Carlos/Xilinx/project 34 segment/project_34_segment/project_34_segment.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Juan Carlos/Xilinx/project 34 segment/project_34_segment/project_34_segment.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Juan Carlos/Xilinx/project 34 segment/project_34_segment/project_34_segment.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Juan Carlos/Xilinx/project 34 segment/project_34_segment/project_34_segment.srcs/sources_1/new/display_34.vhd}
  {C:/Users/Juan Carlos/Xilinx/project 34 segment/project_34_segment/project_34_segment.srcs/sources_1/new/nombres.vhd}
  {C:/Users/Juan Carlos/Xilinx/project 34 segment/project_34_segment/project_34_segment.srcs/sources_1/new/segment_decoder_34.vhd}
  {C:/Users/Juan Carlos/Xilinx/project 34 segment/project_34_segment/project_34_segment.srcs/sources_1/new/vga_ctrl_640x480_60Hz.vhd}
  {C:/Users/Juan Carlos/Xilinx/project 34 segment/project_34_segment/project_34_segment.srcs/sources_1/new/test_imp.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Juan Carlos/Xilinx/project 34 segment/project_34_segment/project_34_segment.srcs/sources_1/new/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Juan Carlos/Xilinx/project 34 segment/project_34_segment/project_34_segment.srcs/sources_1/new/Basys3_Master.xdc}}]


synth_design -top test_imp -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test_imp.dcp

catch { report_utilization -file test_imp_utilization_synth.rpt -pb test_imp_utilization_synth.pb }
